### PR TITLE
Give the app a bit longer to start up

### PR DESCRIPTION
**Pull request by rebkwok**

### CODE REVIEW

**Review by iaindillingham — APPROVED** [review]
Why does the app need 20 more (seconds?) to start up?

**Comment by rebkwok** [comment]
> Why does the app need 20 more (seconds?) to start up?

30 seconds is a bit arbitrary and is just what job-server users.  It needed increased because 10s wasn't always long enough if it had to run migrations.  This one took 3 reruns before it managed to get the migrations done quickly enough to complete deployment.
https://github.com/opensafely-core/opencodelists/actions/runs/2015184619

**Comment by iaindillingham** [comment]
Got it, thank you!

**Comment by inglesp** [comment]
Sigh!  Could we add a comment about where 30s has come from, and why we think it's enough?

**Pull request merged**
